# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "uhci_hcd" "ehci_pci" "ahci" "firewire_ohci" "usb_storage" "sd_mod" "sr_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ "i915" ];
  boot.kernelModules = [ "i2c-dev" ];
  boot.extraModulePackages = [ ];
  boot.tmpOnTmpfsSize = "50%";
  services.logind.extraConfig = ''
	RuntimeDirectorySize=1G
  '';

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/78f4ce7f-e5dc-4768-9800-84a07b6b99e4";
      fsType = "xfs";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/bda79c02-a9ca-405c-821d-d9da50ff7c85"; 
        priority = 1;
      }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp1s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp2s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;


# Для пользователей в группе i2c
  systemd.udev.rules = [
    "KERNEL==\"i2c-[0-9]*\", GROUP=\"i2c\", MODE=\"0660\""
  ];

}
