# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "amdgpu" "ehci_pci" "ahci" "nvme" "xhci_pci" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = ["amdgpu" ];
  boot.kernelModules = ["amdgpu" "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "none";
      fsType = "tmpfs";
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/081435b7-df56-426c-a121-b58204b2802f";
      fsType = "btrfs";
      options = [ "subvol=nix" "compress=zstd" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/081435b7-df56-426c-a121-b58204b2802f";
      fsType = "btrfs";
      options = [ "subvol=home" "compress=zstd" ];
      neededForBoot = true;
    };

  fileSystems."/home/shpinog/mnt/files" =
  { device = "/dev/disk/by-uuid/04af76ef-a8d9-4ce4-80dd-375339c81164";
    fsType = "ext4";
    options = [ "noauto" "x-systemd.automount" ];
  };

  fileSystems."/home/shpinog/mnt/backup" =
  { device = "/dev/disk/by-uuid/4e52c8ed-2dc3-4796-9ca2-cc2f80b561ff";
    fsType = "ext4";
    options = [ "noauto" "x-systemd.automount" ];
  };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/9464-1E2B";
      fsType = "vfat";
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp7s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
