# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "ehci_pci" "ahci" "nvme" "xhci_pci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/af9ee601-25ff-4e9c-9af1-2e38785b94a6";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/9464-1E2B";
      fsType = "vfat";
    };
    
  fileSystems."/home/shpinog/Games" =
    { device = "/dev/disk/by-uuid/04af76ef-a8d9-4ce4-80dd-375339c81164";
    fsType = "ext4";
    options = 
    [
      "defaults"
    ];
    };

    swapDevices = [ ];

    nixpkgs.hostPlatform = "x86_64-linux";

}
